### ISSUE TITLE
gql2ts

### ISSUE THREAD

**Issue by brettjurgens** [joarwilk/gql2flow#37]
@joarwilk 

Hey...

this repo looks pretty familiar. just wanted to let you know that the v1 of gql2ts supports [flow output](https://github.com/avantcredit/gql2ts/tree/master/packages/language-flow) (and would appreciate any help to improve that) and fixes a bunch of issues with the v0.x versions (which this seems to be based off of)

p.s. in the future, forking, attributing, or maintaining the history would really be nice. i understand that our license is MIT and I have no leg to stand on, but some attribution would go a long way.

**Comment by joarwilk** [comment]
@brettjurgens Hey, I had a link to gql2ts in the top of the readme before but removed it for some honestly unknown reason.

Maybe better to deprecate this and link to gql2ts instead? Better to use a single repo for the same purpose. I dont really have time to maintain it anyway.

**Comment by jwickens** [comment]
Just my 2cents on how this should proceed.
A) @joarwilk should put a deprecation warning on this package and point users to gql2s
B) @joarwilk and @brettjurgens should ask users to report flow issues at  avantcredit/gql2ts#78
C) once that issue has been closed the flow support in gql2ts should be more heavily advertised. Perhaps with a rename.

**Comment by ohjames** [comment]
Definitely should add that deprecation notice, gql2ts does everything this project does and more (with tests).

**Comment by joarwilk** [comment]
Added @ohjames
