### ISSUE TITLE
is this repo still maintained?

### ISSUE THREAD

**Issue by mikestaub** [joarwilk/gql2flow#40]
It has been quite a while since the last release, there are still bugs in the latest published 0.4.5

As far as I know this is still the best GraphQL -> FlowType tool out there. Would you like help maintaining this project?

**Comment by joarwilk** [comment]
I recommend https://github.com/avantcredit/gql2ts

It is maintained and covers everything that this repo does (it has a `flow` flag).

**Comment by mikestaub** [comment]
Thanks for the tip. That repo also has issues with flow support, but they should be resolved in 2.0.

https://github.com/avantcredit/gql2ts/issues/163
